--- !ruby/object:Jumpstart::Configuration
application_name: AgroProcess - Rural Soluções
business_name: Accreditaire LLC
domain: example.com
support_email: bruno@accreditaire.com
default_from_email: Jumpstart <support@example.com>
business_address: 18117 Biscayne Blvd Suite 75, Aventura FL
background_job_processor: async
email_provider: ''
personal_accounts: true
livereload: false
solargraph: true
register_with_account: false
